name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - staging

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
